Create/Destroy methods in Engine class
Ventus218/PPS-23-SGE pull request #20
Opened 2024-06-25 09:54 UTC by RavaMichi

2024-06-26 08:53 UTC, Ventus218 requested changes
Ho capito come mai in TestUtils servono i testLoadSceneXXX, penso che comunque più avanti dovremmo renderne l'utilizzo più chiaro (penso che i test siano un po' difficili da leggere).

2024-06-26 08:53 UTC, Ventus218 commented on doc/05_Implementazione.md
> +La creazione di un game object comporta la chiamata immediata del metodo `onInit` su quest'ultimo. Se si vuole distruggere un oggetto che non è presente nella scena, viene lanciata una `IllegalArgume
Penso che qui ci sia una ripetizione di riga 45

2024-06-26 08:53 UTC, Ventus218 commented on src/main/scala/Engine.scala
> +    private var sceneToChange: Option[Scene] = Option.empty
Penso che sceneToLoad sarebbe più chiaro, sceneToChange sembra riferirsi alla scena che va cambiata (quindi quella vecchia).

2024-06-26 08:53 UTC, Ventus218 commented on src/main/scala/Engine.scala
Non sono convinto che sia una buona idea chiamare onInit, onEnabled e onDeinit direttamente nei metodi di creazione e distruzione degli oggetti.

Analizzando il caso di distruzione:
Se distruggo un oggetto, e viene subito eseguita la sua Deinit è ragionevole pensare che su quell'oggetto non debba più essere chiamato nessun altro metodo.
Però considerando che l'ordine di esecuzione delle Update fosse (oggetto A, oggetto B) se l'oggetto A chiama *destroy* per distruggere B allora su B verrà subito chiamata la onDeinit, ma poi verrà chiamata anche la onUpdate.

Riguardo a init ed enabled non mi vengono in mente casi così eclatanti però direi che se adottiamo un approccio per destroy dobbiamo essere consistenti anche con create, quindi nel caso fossi d'accordo con me che questo cambiamento vada effettuato andrebbe fatto su entrambi i metodi.

Sto sbagliando io da qualche parte oppure concordi?

2024-06-26 14:04 UTC, RavaMichi commented on src/main/scala/Engine.scala
onInit e onEnabled li eseguirei comunque subito alla chiamata di create, altrimenti non ci sarebbe alcuna differenza tra chiamare init/enabled oppure start, invece così c'è più ordine e struttura secondo me.

onDeinit invece va cambiato invece, e lo eseguirei nello stesso momento in cui si esegue anche onStart.

2024-06-27 07:31 UTC, Ventus218 requested changes

2024-06-27 07:31 UTC, Ventus218 commented on doc/05_Implementazione.md
> +quelli appena aggiunti viene chiamato il metodo `onInit` e, se sono abilitati, anche i metodi `onEnabled` e `onStart`.
> e, se sono abilitati, anche i metodi `onEnabled` e `onStart`.

abbiamo detto solo quando si cambia stato quindi io direi solo
> e, se sono abilitati, anche il metodo `onStart`.

2024-06-27 07:31 UTC, Ventus218 commented on doc/05_Implementazione.md
> +La creazione di un game object comporta la chiamata immediata del metodo `onInit` su quest'ultimo e del metodo `onEnabled` se abilitato. Verrà chiamato anche il metodo `onStart` all'inizio del nuovo
Anche nel codice la chiamata ad onInit non è immediata ma avviene quando inizia Il frame successivo, quindi questa frase non è corretta.

2024-06-27 07:43 UTC, Ventus218 approved these changes

2024-06-27 07:43 UTC, Ventus218 commented
Ottimo lavoro!

2024-06-27 11:11 UTC, Corstor approved these changes

2024-06-27 15:07 UTC, merged