Feature/swing input
Ventus218/PPS-23-SGE pull request #23
Opened 2024-06-26 08:13 UTC by Ventus218

2024-06-26 09:14 UTC, Ventus218 commented
Prima di fare review e merge di questo aspetterei di avere su develop i cambiamenti di #22 siccome ci saranno alcune cose da cambiare!

2024-06-27 07:23 UTC, RavaMichi requested changes
E' tutto perfetto, funziona ed e' anche molto carino da programmare. Le uniche cose che mancano secondo me sono degli handler che vengono eseguiti una sola volta, ovvero che sono invocati solamente quando un pulsante passa da Released a Pressed e visceversa. E' un comportamento che puo' essere emulato dai behaviour utilizzando dei boolean per tenere traccia delle pressioni dei tasti, pero' mi piacerebbe che fosse il framework a fornirmi queste funzionalita', cosi' da non doverle programmare io tutte le volte.

Se non e' troppo complicato da fare io gli aggiungerei, perche' li trovo molto utili, se invece ci vuole molto allora direi di ignorare l'aggiunta e ti approvo subito. Fammi sapere cosa ne pensi

2024-06-27 07:35 UTC, Ventus218 commented
> E' tutto perfetto, funziona ed e' anche molto carino da programmare. Le uniche cose che mancano secondo me sono degli handler che vengono eseguiti una sola volta, ovvero che sono invocati solamente quando un pulsante passa da Released a Pressed e visceversa. E' un comportamento che puo' essere emulato dai behaviour utilizzando dei boolean per tenere traccia delle pressioni dei tasti, pero' mi piacerebbe che fosse il framework a fornirmi queste funzionalita', cosi' da non doverle programmare io tutte le volte.
> 
> Se non e' troppo complicato da fare io gli aggiungerei, perche' li trovo molto utili, se invece ci vuole molto allora direi di ignorare l'aggiunta e ti approvo subito. Fammi sapere cosa ne pensi

Va bene, ci guardo!

2024-06-28 07:16 UTC, RavaMichi approved these changes
Bravo

2024-06-28 07:17 UTC, merged